apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ns-list
  namespace: {{ .Release.Namespace | quote }}
data:
  namespaces.json: |
    {
      "optional_name": {{ .Values.optional_name | quote }},
      "namespaces": [
        {{- range .Values.list_namespace }}
        "{{ . }}",
        {{- end }}
      ]
    }
