apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace | quote }}
data:
  custom.conf: |
    # upstream Backend {
    #     # hello is the internal DNS name used by the backend Service inside Kubernetes
    #     server dashboard;
    # }
    server {
        listen 8080;  # Port on which Nginx will listen

        location / {
            root /usr/share/nginx/html;  # Set the root directory for static files
            index index.html;  # Specify the default index file (usually index.html)
        }

        location /kuber {
            proxy_pass http://{{ include "release.shortName" . }}-api:8000;  # Backend service endpoint
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
