apiVersion: v1
kind: Service
metadata:
  name: {{ include "release.shortName" . }}-ui
  namespace: {{ .Values.namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: ui
  selector:
    app: kuberui
