kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "release.shortName" . }}-crb
subjects:
- kind: ServiceAccount
  name: {{ include "release.shortName" . }}-sa
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "release.shortName" . }}-clr
  apiGroup: rbac.authorization.k8s.io