apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "release.shortName" . }}-api
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: kuberapi
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kuberapi
  template:
    metadata:
      labels:
        app: kuberapi
    spec:
      serviceAccountName: {{ include "release.shortName" . }}-sa
      containers:
        - name: kuberapi
          image: yurasdockers/kuberapi:{{ .Values.api.image.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: 128Mi
              cpu: "100m"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
