apiVersion: v1
kind: Service
metadata:
  name: {{ include "release.shortName" . }}-api
  namespace: {{ .Values.namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: api
  selector:
    app: kuberapi
