---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-api-dp
  labels:
    app: kuberapi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kuberapi
  template:
    metadata:
      labels:
        app: kuberapi
    spec:
      containers:
        - name: kuberapi
          image: yurasdockers/kuberapi:0.1.1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      serviceAccountName: kuber-api-sa

---
apiVersion: v1
kind: Service
metadata:
  name: kuber-api-svc
spec:
  type: NodePort
  selector:
    app: kuberapi
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 32010