---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuber-api-sa
  namespace: app
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuber-api-clr
  labels:
    app: kuberapi
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
- apiGroups: [""]
  resources: 
  - nodes
  - nodes/proxy
  verbs: ["list", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuber-api-crb
subjects:
- kind: ServiceAccount
  name: kuber-api-sa
  namespace: app
roleRef:
  kind: ClusterRole
  name: kuber-api-clr
  apiGroup: rbac.authorization.k8s.io