---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuber-api
  namespace: app
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuber-api
  labels:
    app: kuberapi
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuber-api
subjects:
- kind: ServiceAccount
  name: kuber-api
  namespace: app
roleRef:
  kind: ClusterRole
  name: kuber-api
  apiGroup: rbac.authorization.k8s.io