# Use the official Nginx image as a parent image
FROM nginx:latest

# Set the working directory in the container
WORKDIR /usr/share/nginx/html

# Copy the frontend files into the container at /usr/share/nginx/html
COPY . .
